### ISSUE TITLE
Is possible validate the integrity of data in a relationship?

### ISSUE THREAD

**Issue by kevinnascimento** [nolanlawson/relational-pouch#46] opened 2015-10-06 01:19 UTC
Is possible validate the integrity of data in a relationship?

For example, in the documentation, an author has many books.

```
db.setSchema([
  {
    singular: 'author',
    plural: 'authors',
    relations: {
      'books': {hasMany: 'book'}
    }
  },
  {
    singular: 'book',
    plural: 'books',
    relations: {
      'author': {belongsTo: 'author'}
    }
  }
]);

```

If I add an author with a book code that does not exist. Is possible validate?

```
db.rel.save ('author', {
   name: 'Stephen King'
   id: 19
   books: [100]
}) ....
```

In this case, the item 100 does not exist.

Thank you.

**Comment by nolanlawson** [comment] 2015-10-17 16:29
Currently it does not validate, but that would be a welcome feature to add! :)

**Comment by FlipOneDev** [comment] 2015-10-31 14:36
+1. This would be an awesome feature, making relational-pouch even more robust. This properly belongs at the top of the priority list.

**Comment by giorgiofellipe** [comment] 2015-11-18 17:04
+1

**Comment by nolanlawson** [comment] 2015-11-23 02:17
I would close this issue as a duplicate of https://github.com/nolanlawson/relational-pouch/issues/24.

The basic issue is that in a system like CouchDB that replicates documents in any order with no guarantee of delivery time, the database can *always* be in an inconsistent. Parents can be replicated before children, docs can be in different state of conflict... you get the idea.

The one thing that it's theoretically possible for this lib to do is at least *inform* people of the current state of consistency, and resolve any missing data at read-time. I'm not sure how it would do that, but it could.

**Closed by nolanlawson** 2015-11-23 02:17 UTC
