### ISSUE TITLE
Can't find an object if one of it's 'belongsTo' parents doesn't reference it anymore.

### ISSUE THREAD

**Issue by egoossens** [nolanlawson/relational-pouch#39] opened 2015-08-28 09:17 UTC
When a relation is broken, it's not even possible to find the child element anymore.
I agree that relations shouldn't get broken, but I'm not sure this is the best behaviour.
Perhaps only returning the object, without it's parent would be better.

```javascript
describe('broken relation test', function() {

	var testPouch2;

	before(function() {

		var authorModel = {
			singular:'author',
			plural:'authors',
			relations:{
				books:{hasMany:'books'}
			}
		};
		var bookModel = {
			singular:'book',
			plural:'books',
			relations:{
				author:{belongsTo:'author'}
			}
		};
		var librarySchema = [authorModel, bookModel];
		testPouch2 = new PouchDb('https://user:pass@somecouch.com/library');
		testPouch2.setSchema(librarySchema);

		var john = {
			name:'John Doe',
			books: [
// Breaking the relation, 'ISBN12341234',
			'ISBN5759759'
			],
			id:'jdoe'
		};
		var book1 = {
			title:'Great book',
			id:'ISBN5759759',
			author:'jdoe'
		};
		var book2 = {
			title:'Awesome book',
			id:'ISBN12341234',
			author:'jdoe'
		};

		return testPouch2.rel.save('book', book1)
		.then(function() {
			return testPouch2.rel.save('book', book2);
		})
		.then(function() {
			return testPouch2.rel.save('author', john);
		});				

	});

	it('should return at least the book that we\'re looking for', function() {
		return testPouch2.rel.find('book', 'ISBN12341234')
		.then(function(books) {			
			expect(books['books'][0].id).to.equal('ISBN12341234');
// This fails because only the author and the book it references are returned.
		});
	});
});
```
Just curious what you're opinion is on this behaviour.
I'll try submitting a PR if I find the time to dive into the rel#find method's code.

**Comment by nolanlawson** [comment] 2015-08-29 01:44
Yeah, I believe I designed this thing such that relations have to be mutual - if they are inconsistent between parent and child, then weird stuff starts to happen. IIRC Ember Data also has this design property.

I can't think of a reasonable way to resolve it except to either say that 1) parents always win, 2) children always win, or 3) you have to keep the two in sync, and too bad if you don't. Out of curiosity, is this an issue you ran into in the wild?

**Comment by egoossens** [comment] 2015-08-29 07:51
Yes I'm building an object class based on PouchDB and relational-pouch. In my Obj#delete method I first removed the reference to the to-be-deleted object from its parents (belongsTo) and then wanted to actually delete it from the pouch using the find/del pattern. That's where the find failed and I got this behavior. I got it to work by doing the reverse. It also worked by deleting using the base PouchDB methods (get/deleted=true/put). 

I understand this is an errory case but as I ran into it I just wanted to have your opinion. My opinion is that a find should always at least return what you're trying to find (if it's there), maybe omitting the related docs if the relation is broken. 

A side question, do you know a piece of software that does what I'm trying to build, i.e. provide an object that has methods to do CRUD taking relations into account (like ActiveRecord in Rails) but with Couch/Pouch  as the data source?

**Comment by nolanlawson** [comment] 2015-08-29 15:29
No, relational-pouch is the only one I'm aware of. Also, I should note that CouchDB veterans will tell you that, when you're trying to store relational data in CouchDB, you need to resolve any inconsistencies at query time anyway, because e.g. what happens if there's a sync conflict in a child but not in a parent?  Or what if replication occurs, and the parent replicates before the child but a user query occurs between the two?

I admit I did not do a great job of solving these problems in this plugin - e.g. see https://github.com/nolanlawson/relational-pouch/issues/24. If you'd like to contribute the fix, though, I'd be happy to accept it. :) Looks like you've already got a test to reproduce it, which is awesome; as for how to fix it, I would lean towards whatever Ember Data does to solve this problem, because 99% of the users of this plugin are via `ember-pouch`.

**Comment by nolanlawson** [comment] 2015-10-04 17:41
Closing as dup of #24. This is still a serious issue btw.

**Closed by nolanlawson** 2015-10-04 17:41 UTC
